home/urls.py
from django.urls import path
from .import views


app_name = 'home'
urlpatterns = [
    path('',views.invoice_list,name='home'),
    path('invoice/detail/<int:pk>/', views.invoice_detail, name='invoice_detail'),
    path('create_view/', views.create_view, name='create_view'),
    path('update/<int:pk>/', views.invoice_update_view , name='invoice_update_view'),
    path('delete_view/<int:pk>/', views.delete_view, name='delete_view'),
    path('my_view/',views.my_view, name='my_view'),
    path('chart/',views.save_chart, name='chart'),
    path('product',views.product_list,name='product'),
    path('product/details/<int:pk>/', views.product_detail.as_view(), name='product_detail'),
    path('product/create_view/', views.product_create_view, name='product_create_view'),
    path('product/update/<int:pk>/', views.product_update_view , name='product_update_view'),
    path('product/delete_view/<int:pk>/', views.product_delete_view, name='product_delete_view'),
    path('product/my_view/',views.product_my_view, name='product_my_view'),


]

web/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.db.models.signals import post_save
from django_jalali.db import models as jmodels


class Invoice(models.Model):
    form_contract = models.CharField(max_length=300)
    company_name = models.CharField(max_length=300)
    address = models.CharField(max_length=300,null=True)
    name_of_the_company_manager = models.CharField(max_length=300)
    date_of_contract = models.DateField()
    contract_number = models.IntegerField()
    nationalid = models.CharField(max_length=300)
    telephone = models.CharField(max_length=300)
    mobile = models.CharField(max_length=300)
    contract_price = models.IntegerField()
    change = models.BooleanField(default=True)
    update = models.DateField(auto_now=True)
    date_of_cash_deposit = models.DateField()
    cash_deposit_amount = models.BigIntegerField()
    contract_type = models.CharField(max_length=300)
    overdue_account = models.IntegerField(null=True,blank=True)
    company_address = models.CharField(max_length=300)
    marketer = models.CharField(max_length=300)
    description = models.CharField(max_length=300)
    printing_cost = models.IntegerField()
    print_account_balance = models.IntegerField()
    print_the_deposited_amount = models.IntegerField()

    def save(self, *args, **kwargs): 
        self.overdue_account = int(self.contract_price) - int(self.cash_deposit_amount)
        super().save(*args, **kwargs)
    


class Product(models.Model):
    salary = models.CharField(max_length=300)
    name = models.CharField(max_length=300)
    phone_number = models.IntegerField()
    check_in_check_out = models.IntegerField()
    check_registration = models.IntegerField()
    due_date = models.DateField()
    change = models.BooleanField(default=True)
    update = models.DateField(auto_now=True)
    the_row_number = models.IntegerField()
    date_received = models.DateField()
    name_of_assignor = models.CharField(max_length=300)
    registered_check = models.IntegerField()
    bank_name = models.CharField(max_length=300)
    branch_name = models.CharField(max_length=300)
    check_number = models.IntegerField()
    check_amount = models.IntegerField()
    account_number =  models.IntegerField()
    due_date = models.DateField()
    pay_to = models.CharField(max_length=300)
    date = models.DateField()
    check_and_out = models.CharField(max_length=300)
    phone_number_of_the_owner_of_the_check = models.IntegerField()
    national_code = models.IntegerField()
    description = models.CharField(max_length=300)

    
   
    def __str__(self):
        return self.name

class Chart(models.Model):
    name = models.CharField(max_length=50, blank =True, null=True)
    company_name = models.CharField(max_length=300)
    overdue_account = models.IntegerField(null=True,blank=True)
    check_amount = models.IntegerField()
    update = models.DateTimeField(auto_now = True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True ,null=True)
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE,  blank=True, null=True)

    
    
    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        old_data = Chart.objects.filter(product__exact=self.product ,invoice__exact=self.invoice ,check_amount__exact=self.check_amount )
        if not old_data.exists():
            return super(Chart, self).save(*args, **kwargs)    




def product_post_saved(sender, instance, created, *args, **kwargs):
    data = instance
    if data.change == False:
        Chart.objects.create(product=data,check_amount=data.check_amount,update=data.update,company_name=data.name)

post_save.connect(product_post_saved, sender =Product)


def invoice_post_saved(sender, instance, created, *args, **kwargs):
    data = instance
    if data.change == False:
        Chart.objects.create(invoice=data,overdue_account=data.overdue_account,update=data.update,company_name=data.company_name)

post_save.connect(invoice_post_saved, sender =Invoice)

home/forms.py
from .models import Invoice, Product
from django import forms




class InvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        # exclude = ['date_of_contract', ]
        fields = "__all__" 





class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__" 
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'check_amount': forms.TextInput(attrs={'class': 'form-control'}),

        }

home/views.py
from django.shortcuts import render,redirect ,get_object_or_404
from .forms import InvoiceForm ,ProductForm
from .models import Invoice , Product , Chart
import datetime
from django.views import View






def invoice_list(request):
    invoices = Invoice.objects.all()
    form = InvoiceForm()
    context = {
        'invoices': invoices,
        'form': form,
    }
    return render(request, 'home.html', context)
  

def invoice_detail(request, pk):
    invoice = get_object_or_404(Invoice, id=pk)
    form = InvoiceForm()
    context = {
        'invoice': invoice,
        'form': form,
    }

    return render(request, 'detail.html', context)

# class invoice_detail(View):
#     def setup(self, request, *args, **kwargs):
#         self.product = get_object_or_404(Invoice, id=kwargs['pk'])
#         self.change = Chart.objects.filter(invoice_id=kwargs['pk'])
       
        
#         return super().setup(request,*args,**kwargs)


    
#     def get(self, request, *args, **kwargs):
#         # invoice = get_object_or_404(Product, id = self.kwargs["pk"])
#         obj = Invoice.objects.get(id = self.kwargs["pk"])
#         form = InvoiceForm()
#         # date = obj.values_list("update ", flat=True)
#         # price = obj.values_list("overdue_account", flat=True)
#         context = {
#         'obj': obj,
#         'form': form,
#         'date':obj.update,
#         'price':obj.overdue_account,
#         }
#         print (context)
#         return render(request, 'detail.html', context)


def save_chart(request):
    products = Invoice.objects.values('product').distinct()
    for product in products:
        prices = Invoice.objects.filter(product=product['product']).values_list('check_amount', flat=True)
        dates = Invoice.objects.filter(product=product['product']).values_list('date', flat=True)

        
        chart = Chart(product=product['product'],
                      prices=','.join(str(price) for price in prices),
                      dates=','.join(str(date) for date in dates))
        chart.save()

    return render(request, 'chart_saved.html')
    




def create_view(request):
    if request.method == 'POST':
        form = InvoiceForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:home')
    else:
        form = InvoiceForm()
    return render(request, 'create.html', {'form': form})

    

    
def invoice_update_view(request, pk):
    invoice_obj = get_object_or_404(Invoice, pk=pk)
    form = InvoiceForm(request.POST or None, instance=invoice_obj)
    context = {
        'form': form,
    }

    if form.is_valid():
        form.save()
        return redirect('home:home')

    return render(request, 'invoice_update_view.html', context)

   

def delete_view(request, pk):
    item = get_object_or_404(Invoice, pk=pk)
    if request.method == 'POST':
        item.delete()
        return redirect('home:home')
    return render(request, 'delete.html', {'item': item})


def my_view(request):
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')
    events = None
    if start_date and end_date:
        events = Invoice.objects.filter(date_of_contract__range=(start_date, end_date))

    return render(request, 'my_view.html', {'events': events})


# def index(request):
#     products = Product.objects.all()
#     if request.method == 'POST':
#         form = ProductForm(request.POST)
#         if form.is_valid():
#             form.save()
#         return redirect('home:index')
#     else:
#         form = ProductForm()

#     context = {
#         'products': products,
#         'form': form,
#     }
#     return render(request,'index.html',context)





def product_list(request):
    products = Product.objects.all()
    form = ProductForm()
    context = {
        'products': products,
        'form': form,
    }
    return render(request, 'product.html', context)
  

# def product_detail(request, pk):
#     product = get_object_or_404(Product, id=pk)
#     form = ProductForm()

#     context = {
#         'product': product,
#         'form': form,
#     }

#     return render(request, 'product_detail.html', context)




class product_detail(View):
    def setup(self, request, *args, **kwargs):
        self.product = get_object_or_404(Product, id=kwargs['pk'])
        self.change = Chart.objects.filter(product_id=kwargs['pk'])
       
        
        return super().setup(request,*args,**kwargs)


    # def product_detail(request, pk):
    def get(self, request, *args, **kwargs):
        obj = Product.objects.get(id = self.kwargs["pk"])
        form = ProductForm()
        context = {
        'obj': obj,
        'form': form,
        'date':obj.update,
        'price':obj.check_amount,
        }
        return render(request, 'product_detail.html', context)



        


def product_create_view(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:product')
    else:
        form = ProductForm()
    return render(request, 'product_create.html', {'form': form})

    

    
def product_update_view(request, pk):
    product_obj = get_object_or_404(Product, pk=pk)
    form = ProductForm(request.POST or None, instance=product_obj)
    context = {
        'form': form,
    }

    if form.is_valid():
        form.save()
        return redirect('home:producte')

    return render(request, 'product_update_view.html', context)

   

def product_delete_view(request, pk):
    item = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        item.delete()
        return redirect('home:product')
    return render(request, 'delete.html', {'item': item})


def product_my_view(request):
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')
    events = None
    if start_date and end_date:
        events = Invoice.objects.filter(date_of_contract__range=(start_date, end_date))

    return render(request, 'product_my_view.html', {'events': events})

home/templates/base.html
<!doctype html>
<html lang="fa" dir="rtl">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
    {% block css %}{% endblock %}
</head>
<body>
    {% include 'navbar.html' %}
    {% include 'message.html' %}
    {% block body %}{% endblock %}
    {% block script %}{% endblock %}
    
    </body>
</html>

home/templates/chart_saved.html
{% extends 'base.html' %}
{% block script %}

<head>
    <script
    src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js">
    </script>
</head>
<body>
  <canvas id="myChart" style="width:100%;max-width:700px"></canvas>

  <script>
      const myChart = new Chart("myChart", {
        type: "scatter",
        data: {},
        options: {}
      });
      var xValues = [];
      var yValues = [];
      var barColors = ["red", "green","blue","orange","brown"];

      new Chart("myChart", {
      type: "bar",
      data: {
        labels: [
        {% for i in change %} {% if products.id == i.product_id %} '{{ i.update }}'  {% endif %} {% endfor %}],

        datasets: [{
          backgroundColor:[
            {% for i in change %} '{{ i.color }}' ,{% endfor %}
        ],
          barColors,
          data: yValues
        }]
      },
      });
  </script>
</body>

{% endblock %}

home/templates/delete.html
{% extends 'base.html' %}

{% block body %}
  <form method="post">
    {% csrf_token %}
    <button type="submit">حذف</button>

  </form>
{% endblock %}

home/templates/event_list.html
{% extends 'base.html' %}

{% block body %}
<form method="get">
    {{ form.as_p }}
    <button type="submit">جستجو</button>
  </form>
  
  <ul>
    {% for Invoice in events %}
      <li>{{ Invoice.name }} - {{ Invoice.start_date }}</li>
    {% empty %}
      <li>هیچ رویدادی پیدا نشد.</li>
    {% endfor %}
  </ul>

home/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<!-- <link rel="stylesheet" type="text/css" href="{% static 'home/home.css' %}"> -->
<script src="https://cdn.tailwindcss.com"></script>
{% endblock %}

{% block body %}
<div class="max-w-7xl flex mx-auto  ">
    <div class="flex flex-col p-4 justify-center w-full ">
        <div
            class="flex flex-row items-center justify-start  gap-2 w-[300px] bg-white border border-solid border-blue-500 rounded p-2 w-full ">
            {% for invoice in invoices %}
            <a class="font-bold text-md text-white bg-blue-400 p-2 px-4 rounded-lg "
                href="{% url 'home:invoice_detail' invoice.id %}">{{ invoice.company_name }}</a>
            {% endfor %}
            <button class="bg-red-500 p-2 px-4 rounded text-white font-bold "><a
                    href="{% url 'home:create_view' %}">ایجاد فاکتور جدید</a></button>
            <button class="bg-red-500 p-2 px-4 rounded text-white font-bold "><a
                    href="{% url 'home:my_view' %}">از تاریخ</a></button>
            <button class="bg-red-500 p-2 px-4 rounded text-white font-bold "><a
                    href="{% url 'home:my_view' %}">تا تاریخ</a></button>
            
        
        </div>
    </div>
</div>

{% endblock %}

home/templates/index.html
<!-- {% extends 'base.html' %}


{% block script %}
   <h2>index page</h2>
   <div class="row mt-2">
        <div class="col-md-4 mt-2">
             <h3>Add Data</h3>
             <hr>
             <form action="" method="post">

                {% csrf_token %}
                {{form}}
                
                <input class="btn btn-success mt-2" type="submit" value="Add Data">

             </form>
        </div>
     
        <div class="tab-pane fade" id="product-shipping-tab" role="tabpanel"
                                     aria-labelledby="product-shipping-link">
                                    <div class="product-desc-content">
                                        <h3>change price</h3>
                                        <canvas id="myChart" width="100" height="100"></canvas>
                                        <script>
                                            var ctx = document.getElementById('myChart').getContext('2d');
                                            var myChart = new Chart(ctx, {
                                                type: 'bar',
                                                data: {
                                                    labels: [
                                                        {% for i in change %} {% if products.id == i.product_id %} '{{ i.update }}'  {% endif %} ,{% endfor %}],
                                                    datasets: [{
                                                        label: '# of Votes',
                                                        data: [
                                                            {% for i in change %} {% if products.id == i.product_id %} {{ i.check_amount }}  {% endif %} ,{% endfor %}],
                                                        backgroundColor: [
                                                            {% for i in change %} '{{ i.color }}' ,{% endfor %}

                                                        ],
                                                        borderColor: [
                                                            'rgba(255, 99, 132, 1)',
                                                            'rgba(54, 162, 235, 1)',
                                                            'rgba(255, 206, 86, 1)',
                                                            'rgba(75, 192, 192, 1)',
                                                            'rgba(153, 102, 255, 1)',
                                                            'rgba(255, 159, 64, 1)'
                                                        ],
                                                        borderWidth: 1
                                                    }]
                                                },
                                                options: {
                                                    scales: {
                                                        yAxes: [{
                                                            ticks: {
                                                                beginAtZero: true
                                                            }
                                                        }]
                                                    }
                                                }
                                            });
                                        </script>
               
            <div class="row">
              <!-- <canvas id="myChart" width="600" height="300"></canvas> -->
            </div>
        </div>
   </div>





{% endblock %} -->

home/templates/invoice_update_view.html
{% extends 'base.html' %}

{% block body %}
  <form action="." method="post">
    {% csrf_token %}
    <div class="p-2">
      <label>فرم قرارداد</label>
        <input type="text" value="{{ form.form_contract.value }}" name="form_contract">
    </div>
    <div class="p-2">
      <label>نام شرکت</label>
        <input type="text" value="{{ form.company_name.value }}" name="company_name">
    </div>
    <div class="p-2">
      <label>آدرس</label>
        <input type="text" value="{{ form.address.value }}" name="address">
    </div>
    <div class="p-2">
      <label>نام مدیر شرکت</label>
        <input type="text" value="{{ form.name_of_the_company_manager.value }}" name="name_of_the_company_manager">
    </div>
    <div class="p-2">
      <label>تاریخ عقد قرارداد</label>
        <input type="text" value="{{ form.date_of_contract.value|date:'Y-m-d'}}" name="date_of_contract">
    </div>    
      <div class="p-2">
      <label>شماره قرار داد</label>
        <input type="text" value="{{ form.contract_number.value }}" name="contract_number">
    </div>
    <div class="p-2">
      <label>شناسه ملی</label>
        <input type="text" value="{{ form.nationalid.value }}" name="nationalid">
    </div>
    <div class="p-2">
      <label>تلفن ثابت</label>
        <input type="text" value="{{ form.telephone.value }}" name="telephone">
    </div>
    <div class="p-2">
      <label> شماره همراه</label>
        <input type="text" value="{{ form.mobile.value }}" name="mobile">
    </div>
    <div class="p-2">
      <label>قیمت قرارداد</label>
        <input type="text" value="{{ form.contract_price.value }}" name="contract_price">
    </div>
    <div class="p-2">
      <label>تاریخ بیعانه نقدی </label>
      <input type="text" value="{{ form.date_of_cash_deposit.value|date:'Y-m-d'}}" name="date_of_cash_deposit">
    </div>
    <div class="p-2">
      <label> مبلغ بیعانه نقدی</label>
        <input type="text" value="{{ form.cash_deposit_amount.value }}" name="cash_deposit_amount">
    </div>
    <div class="p-2">
      <label> نوع قرارداد</label>
        <input type="text" value="{{ form.contract_type.value }}" name="contract_type">
    </div>
    <div class="p-2">
      <label>حساب معوقه</label>
        <input type="text" value="{{ form.overdue_account.value }}" name="overdue_account">
    </div>
    <div class="p-2">
      <label> آدرس شرکت</label>
        <input type="text" value="{{ form.company_address.value }}" name="company_address">
    </div>
    <div class="p-2">
      <label>بازاریاب </label>
        <input type="text" value="{{ form.marketer.value }}" name="marketer">
    </div>
    <div class="p-2">
      <label>توضیحات </label>
        <input type="text" value="{{ form.description.value }}" name="description">
    </div>
    <div class="p-2">
      <label>هزینه چاپ</label>
        <input type="text" value="{{ form.printing_cost.value }}" name="printing_cost">
    </div>
    <div class="p-2">
      <label>مانده حساب چاپ</label>
        <input type="text" value="{{ form.print_account_balance.value }}" name="print_account_balance">
    </div>
    <div class="p-2">
      <label>مبلغ واریزشده چاپ</label>
        <input type="text" value="{{ form.print_the_deposited_amount.value }}" name="print_the_deposited_amount">
    </div>
    <input type="submit" value="ویرایش">
  </form>
  {% if form.errors %}
        {% for field in form %}
            {% if field.errors %}
                {% for error in field.errors %}
                    {{ field.label }} : {{ error }}
                {% endfor %}
            {% endif %}
        {% endfor %}
    {% endif %}

    {% if form.non_field_errors %}
        {{ form.non_field_errors }}
    {% endif %}
{% endblock %}


 
  
  

home/templates/my_view.html
{% extends 'base.html' %}

{% block body %}
<form action="{% url 'home:my_view' %}" method="get">

    <input type="date" name="start_date">
    <input type="date" name="end_date">
    <input type="submit" value="search">
</form>
  
  <ul>
    {% for Invoice in events %}
      <li>{{ Invoice.form_contract }}</li>
    {% empty %}
      <li>هیچ رویدادی پیدا نشد.</li>
    {% endfor %}
  </ul>
  {% endblock %}

home/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'home/home.css' %}">
<script src="https://cdn.tailwindcss.com"></script>
{% endblock %}

{% block body %}
<div class="max-w-7xl flex mx-auto  ">
    <div class="flex flex-col p-4 justify-center w-full ">
        <div
            class="flex flex-row items-center justify-start  gap-2 w-[300px] bg-white border border-solid border-blue-500 rounded p-2 w-full ">
            {% for product in products %}
            <a class="font-bold text-md text-white bg-blue-400 p-2 px-4 rounded-lg "
                href="{% url 'home:product_detail' product.id %}">{{ product.name }}</a>
            {% endfor %}
            <button class="bg-red-500 p-2 px-4 rounded text-white font-bold "><a
                    href="{% url 'home:product_create_view' %}">ایجاد فاکتور جدید</a></button>
            <button class="bg-red-500 p-2 px-4 rounded text-white font-bold "><a
                    href="{% url 'home:product_my_view' %}">از تاریخ</a></button>
            <button class="bg-red-500 p-2 px-4 rounded text-white font-bold "><a
                    href="{% url 'home:product_my_view' %}">تا تاریخ</a></button>
        </div>
    </div>
</div>

{% endblock %}

home/templates/product_create.html
{% extends 'base.html' %}

{% block body %}
<form action="." method="post">
  {% csrf_token %}
  <div class="p-2">
    <label>تنخواه </label>
      <input type="text" value="{{ form.salary.value }}" name="salary">
  </div>
  <div class="p-2">
    <label>نام</label>
      <input type="text" value="{{ form.name.value }}" name="name">
  </div>
  <div class="p-2">
    <label>تماس</label>
      <input type="text" value="{{ form.phone_number.value }}" name="phone_number">
  </div>
  <div class="p-2">
    <label>ورود/خروج چک</label>
      <input type="text" value="{{ form.check_in_check_out.value }}" name="check_in_check_out">
  </div>
  <div class="p-2">
    <label>ثبت چک</label>
      <input type="text" value="{{ form.check_registration.value }}" name="check_registration">
  </div>
  <div class="p-2">
    <label>تاریخ سررسید</label>
      <input type="text" value="{{ form.due_date.value }}" name="due_date">
  </div>
  <div class="p-2">
    <label>شماره ردیف</label>
      <input type="text" value="{{ form.the_row_number.value }}" name="the_row_number">
  </div>
  <div class="p-2">
    <label>تاریخ دریافت</label>
      <input type="text" value="{{ form.date_received.value }}" name="date_received">
  </div>
  <div class="p-2">
    <label>نام واگذارنده</label>
      <input type="text" value="{{ form.name_of_assignor.value }}" name="name_of_assignor">
  </div>
  <div class="p-2">
    <label>چک ثبت شده</label>
      <input type="text" value="{{ form.registered_check.value }}" name="registered_check">
  </div>
  <div class="p-2">
    <label>نام بانک</label>
      <input type="text" value="{{ form.bank_name.value }}" name="bank_name">
  </div>
  <div class="p-2">
    <label>نام شعبه</label>
      <input type="text" value="{{ form.branch_name.value }}" name="branch_name">
  </div>
  <div class="p-2">
    <label>شماره چک</label>
      <input type="text" value="{{ form.check_number.value }}" name="check_number">
  </div>
  <div class="p-2">
    <label>مبلغ چک (ریال)</label>
    <input type="text" value="{{ form.check_amount.value }}" name="check_amount">
  </div>
  <div class="p-2">
    <label>شماره حساب</label>
      <input type="text" value="{{ form.account_number.value }}" name="account_number">
  </div>
  <div class="p-2">
    <label>تاریخ سررسید</label>
      <input type="text" value="{{ form.due_date.value }}" name="due_date">
  </div>
  <div class="p-2">
    <label>در وجه</label>
      <input type="text" value="{{ form.pay_to.value }}" name="pay_to">
  </div>
  <div class="p-2">
    <label>تاریخ</label>
      <input type="text" value="{{ form.date.value }}" name="date">
  </div>
  <div class="p-2">
    <label>چک ورودی/خروجی</label>
      <input type="text" value="{{ form.check_and_out.value }}" name="check_and_out">
  </div>
  <div class="p-2">
    <label>تلفن صاحب چک</label>
      <input type="text" value="{{ form.phone_number_of_the_owner_of_the_check.value }}" name="phone_number_of_the_owner_of_the_check">
  </div>
  <div class="p-2">
    <label>کدملی</label>
      <input type="text" value="{{ form.national_code.value }}" name="national_code">
  </div>
  <div class="p-2">
    <label>توضیحات</label>
      <input type="text" value="{{ form.description.value }}" name="description">
  </div>
  <input type="submit" value="جدید">
</form>
{% if form.errors %}
        {% for field in form %}
            {% if field.errors %}
                {% for error in field.errors %}
                    {{ field.label }} : {{ error }}
                {% endfor %}
            {% endif %}
        {% endfor %}
    {% endif %}

    {% if form.non_field_errors %}
        {{ form.non_field_errors }}
    {% endif %}
{% endblock %}

home/templates/product_detail.html
{% extends 'base.html' %}

{% block body %}
<p>{{ product.name }}</p>
    <a href="{% url 'home:product_update_view' product.id %}">ویرایش</a>
    <a href="{% url 'home:product_delete_view' product.id %}">حذف</a>

{% endblock %}

home/templates/product_event_list.html
{% extends 'base.html' %}

{% block body %}
<form method="get">
    {{ form.as_p }}
    <button type="submit">جستجو</button>
  </form>
  
  <ul>
    {% for Product in events %}
      <li>{{ Product.name }} - {{ Product.start_date }}</li>
    {% empty %}
      <li>هیچ رویدادی پیدا نشد.</li>
    {% endfor %}
  </ul>

home/templates/product_my_view.html
{% extends 'base.html' %}

{% block body %}
<form action="{% url 'product:product_my_view' %}" method="get">

    <input type="date" name="start_date">
    <input type="date" name="end_date">
    <input type="submit" value="search">
</form>
  
  <ul>
    {% for Product in events %}
      <li>{{ Product.date }}</li>
    {% empty %}
      <li>هیچ رویدادی پیدا نشد.</li>
    {% endfor %}
  </ul>
  {% endblock %}