accounts/urls.py
from django.urls import path
from .import views

app_name ='accounts'
urlpatterns =[
    path('register/',views.register,name='register'),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('profile/', views.user_profile, name='profile'),
    path('update/',views.user_update, name='update'),
    path('change/',views.change_password,name='change'),
    # path('login_phone/',views.phone,name='phone'),
    # path('verify/',views.verify,name='verify'),
]

home/urls.py
from django.urls import path
from .import views


app_name = 'home'
urlpatterns = [
    path('',views.invoice_list,name='home'),
    path('invoice/detail/<int:pk>/', views.invoice_detail, name='invoice_detail'),
    path('create_view/', views.create_view, name='create_view'),
    path('update/<int:pk>/', views.invoice_update_view , name='invoice_update_view'),
    path('delete_view/<int:pk>/', views.delete_view, name='delete_view'),
    path('my_view/',views.my_view, name='my_view'),
    path('chart/',views.save_chart, name='chart'),
    path('product',views.product_list,name='product'),
    path('product/details/<int:pk>/', views.product_detail.as_view(), name='product_detail'),
    path('product/create_view/', views.product_create_view, name='product_create_view'),
    path('product/update/<int:pk>/', views.product_update_view , name='product_update_view'),
    path('product/delete_view/<int:pk>/', views.product_delete_view, name='product_delete_view'),
    path('product/my_view/',views.product_my_view, name='product_my_view'),


]

web/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from .usermanager import UserManager
# from.phone_field import phoneField

# error = {
#     'min_length':'حداقل باید 5 کاراکتر باشد',
#     'required':'این فیلد اجباری است',
#     'Invalid':'ایمیل شما نا معتبر است'
# }


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True)
    # email = models.EmailField(unique=True ,error_messages= error)
    first_name = models.CharField(max_length=100)
    # first_name = models.CharField(max_length=10,min_length =5,error_messages=error)
    last_name = models.CharField(max_length=300)
    password = models.CharField(max_length=300)

    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    backend = 'accounts.backend.EmailBckend'

    def __str__(self):
        return self.email


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=300)
    address = models.CharField(max_length=300,null=True,blank=True)

    def save_profile_user(sender, **kwargs):
        if kwargs['created']:
            profile_user = UserProfile(user=kwargs['instance'])
            profile_user.save()
    post_save.connect(save_profile_user, sender=User)

    def __str__(self):
        return self.user.email
    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django import forms




class UserRegister(UserCreationForm):
    class Meta:
        model = User
        fields =['email', 'first_name', 'last_name', 'password1', 'password2']


    def clean_user_name(self):
        user = self.cleaned_data['user_name']
        if User.objects.filter(username = user).exists():
            raise forms.ValidationError('user exist')
        return user
    
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email = email).exists():
            raise forms.ValidationError('این ایمیل از قبل وجود دارد')
        return email

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 != password2:
            raise forms.ValidationError('password not match')
        elif len(password2) < 8:
            raise forms.ValidationError('password to short')
        elif not any (x.isupper() for x in password2):
            raise forms.ValidationError('پسورد شما حداقل باید یک حروف بزرگ داشته باشد')
        return password1
    
class ProfileUpdateForm(forms.Form):
    class Meta:
        model = User
        fields =['user', 'phone', 'address']

class UserUpdateForm(forms.Form):
    class Meta:
        model = User
        fields =['user', 'phone', 'address']


class UserProfile(forms.Form):
    class Meta:
        model = User
        fields =['user', 'phone', 'address']



# class PhoneForm(forms.Form):
#     phone = forms.IntegerField()

# class CodeForm(forms.Form):
#     code =forms.IntegerField()
    

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from .forms import UserRegister , ProfileUpdateForm , UserUpdateForm, UserProfile 
# from .forms import PhoneForm
from django.contrib.auth import authenticate, login,logout
from django.contrib import messages
from .models import *
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
# from random import randint , CodeForm
# import ghasedak
#authenticateمیاد بررسی میکنه اطلاعاتی که کاربر وارد دیتا بیس وارد کرده وجود داره یاخیر






def register(request):
    if request.method == "POST":
        form = UserRegister(request.POST)
        if form.is_valid():
            form.save()
        return redirect('home:home')
    else:
        form = UserRegister()
    return render(request, 'register.html', {'form':form})
    
def user_login(request):
    if request.method =='POST':
        try:
            user = authenticate(request, email=request.POST.get('email'), password=request.POST.get('password'))
        except:
            user = authenticate(request, email=request.POST.get('email'), password=request.POST.get('password'))
    
        if user is not None:
            login(request,user)
            messages.success(request,'wellcome my site','primary')
            return redirect('home:home')
        else:
            messages.error(request,'email or password wrong','danger')
    return render(request, 'login.html')



def user_logout(request):
    logout(request)
    messages.success(request,'باموفقیت خارج شدید','warning')
    return redirect('home:home')


@login_required(login_url='accounts:login')
def user_profile(request):
    print(request.user.id)
    user = User.objects.all()
    print(user)
    user = User.objects.get(id=request.user.id)
    profile = UserProfile.objects.get(user=user)
    return render(request,'profile.html',{'profile':profile}) 


@login_required(login_url='accounts:login')
def user_update(request):
    if request.method == 'POST':
        user_from = UserUpdateForm(request.POST , instance=request.user)
        profile_form =ProfileUpdateForm(request.POST, instance=request.user.profile)
        if user_from and profile_form.is_valid():
            user_from.save()
            profile_form.save()
            messages.success(request,'update successfuly','success')
            return redirect('accounts:home')
    else:
       user_from = UserUpdateForm(instance=request.user)
       profile = UserProfile.objects.get(user = request.user)
       profile_form =ProfileUpdateForm(instance=profile)
    context ={'user_form':user_from ,'profile_form':profile_form}
    return render(request,'update.html',context)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user , request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            messages.success(request,'پسورد با موفقیت تغییرکرد','success')
            return redirect('accounts:profile')
        else:
            messages.error(request,'پسورد اشتباه است','danger')
            return redirect('accounts:change')
    else:
        form = PasswordChangeForm(request.user)
        return render(request ,'change.html',{'form':form})
    


# def phone(request):
#     if request.method == 'POST':
#         form = PhoneForm(request.POST)
#         if form.is_valid():
#             global random_code ,phone
#             data = form .cleaned_data
#             phone = f"0{data['phone']}"
#             random_code = randint(100,1000)
#             sms = ghasedak.Ghasedak('')
#             sms.send({'message':random_code , 'receptor':phone , 'linenumber':10008566})
#             return redirect('accounts:verify')
#     else:
#         form = PhoneForm
#     return render(request,'phone.html',{'form':form})

# def verify(request):
#     if request.method == 'POST':
#         form = CodeForm(request.post)
#         if form.is_valid():
#             if random_code == form.cleaned_data['code']:
#                 profile = profile.objects.get(phone = phone)
#                 user = user.objects.get(profile__id = profile.id)
#                 login(request,user)
#                 messages.success(request,'hi user')
#                 return redirect('home:home')
#             else:
#                 messages.error(request,'code warning')
#     return render(request,'code.html')

accounts/templates/change.html
{% extends 'base.html' %}
{% block title %} {% endblock %}
{% block body %}
<h1>change password</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">change_password</button>
</form>
{% endblock %}

accounts/templates/code.html
{% extends 'base.html' %}
{% block body %}
<h1>phone login</h1>
<form action="" method="post"></form>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">login</button>

{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}
{% block title %} {% endblock %}
{% block body %}
<h1>login</h1>
<form action="" method="post">
    {% csrf_token %}
    <input type="text" name="email" placeholder="plz email"><br><br>
    <input type="password" name="password" placeholder="plz password"><br><br>
    <button type="submit">login</button>
</form>
{% endblock %}

accounts/templates/message.html
{% if messages %}
    {% for msg in messages %}
        <h3 {% if msg.tags %} class="alert alert-{{msg.tags}}"{% endif %}>{{ msg }}</h3>
    {% endfor %}  
{% endif %}  

accounts/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-white bg-white">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">صفحه اول</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:product' %}">صفحه دوم</a>
          </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">خروج از صفحه کاربری</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:profile' %}">پروفایل</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">ورود به صفحه کاربری</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:register' %}">ثبت نام</a>
        </li>
        {% endif %}
      </ul>
  </div>
</nav>

accounts/templates/phone.html
{% extends 'base.html' %}
{% block body %}
<h1>phone</h1>
    <form action="" method="post"></form>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">send code</button>

{% endblock %}

accounts/templates/profile.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% block body %}
<h1>profile</h1>
<table>
    <tr>
        <th>user :{{profile.user.username}}</th>
    </tr>
    <tr>
        <th>name :{{profile.user.first_name}}</th> 
    </tr>
    <tr>
        <th>email :{{profile.user.email}}</th> 
    </tr>
    <tr>
        <th>phone :{{profile.phone}}</th> 
    </tr>
    <tr>
        <th>address :{{profile.address}}</th> 
    </tr>
</table>
   <a href="{% url 'accounts:update' %}">update</a>
   <a href="{% url 'accounts:change' %}">change password</a>
{% endblock %}

accounts/templates/register.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{%  block body %}
<h1>ثبت نام</h1>
<form method="post" novalidate>
{% csrf_token %}    
    {{form.as_p}}
    <button type="submit">ثبت نام</button>
</form>
<script>
    const username_field = document.getElementsByName('username');
    username_field[0].placeholder = "plz username"
    const Email_address_field = document.getElementsByName('email');
    Email_address_field[0].placeholder = "plz Email_address"
    const first_name_field = document.getElementsByName('first_name');
    first_name_field[0].placeholder = "plz first_name"
    const last_name_field = document.getElementsByName('last_name');
    last_name_field[0].placeholder = "plz last_name"
    const password_field = document.getElementsByName('password1');
    password_field[0].placeholder = "plz password"
</script>
{% endblock %}

accounts/templates/update.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% block body %}
<h1>update profile</h1>
    <form action="" method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit">update</button>
    </form>
{% endblock %}